#!/usr/bin/env escript

% If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
% 
% Find the sum of all the multiples of 3 or 5 below 1000.

main(_) ->
	Multiples = [N || N <- lists:seq(1, 999), N rem 3 =:= 0 orelse N rem 5 =:= 0],
	io:format("Sum of numbers 0 - 1000 that are multiples of 3 or 5: ~w~n", [lists:sum(Multiples)]).