-module('solution-1').
-export([start/0]).

% Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
% 
% 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
% 
% By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

start() ->
	io:format("Sum of even numbers in Fibonacci sequence less than 4,000,000: ~w~n", [sum_even_fib(4000000)]).
	
sum_even_fib(Max) ->
	sum_even_fib(Max, 1, 0, 0).
	
sum_even_fib(Max, Current, Previous, Sum) ->
	Next = Previous + Current,
	if Next > Max -> Sum;
		Next rem 2 > 0 -> sum_even_fib(Max, Next, Current, Sum);
		Next rem 2 =:= 0 -> sum_even_fib(Max, Next, Current, Sum + Next)
	end.